### ISSUE TITLE
[FR] 滑动判定

### ISSUE THREAD

**Issue by podao** [bggRGjQaUbCoE/PiliPalaX#15]
45度滑动时就会从推荐滑到热门/直播页面。
官方版只有水平滑动才可以，判定非常严格。其它种类app也是这样。
用户习惯和水平滑动本身也不多，能不能也判定严格些。

**Comment by podao** [comment]
上滑很容易45度

**Comment by Dome-World** [comment]
> 上滑很容易45度

很好的设计，让我手臂上扬（？）
