### ISSUE TITLE
[Bug] 评论区无法加载

### ISSUE THREAD

**Issue by sgr997** [bggRGjQaUbCoE/PiliPalaX#22]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。
![IMG_8913](https://github.com/user-attachments/assets/1f318ce8-29fe-428a-b9f1-7a72aa100085)

**Comment by bggRGjQaUbCoE** [comment]
开了代理？

**Comment by sgr997** [comment]
> 开了代理？

确实开了代理，试了下关掉代理就正常了，然后我在我的代理软件quantumultx中吧grpc.biliapi.net域名过滤掉就可以了，确实是代理的问题
