### ISSUE TITLE
[Bug] 平板布局下直播播放器: 按键布局超出屏幕、全屏后使用手势返回会短暂切换为竖屏布局

### ISSUE THREAD

**Issue by sharkucn** [bggRGjQaUbCoE/PiliPalaX#23]
### 问题描述
平板布局下打开任意直播间，小窗播放 与 全屏 功能键位于任务栏下且部分超出屏幕，无法触控且任务栏不自动隐藏。(图1)
在收起任务栏、仅保留导航条时，按键有可触控部分。进入全屏后，功能键布局不再超出屏幕，任务栏正常隐藏。

平板布局下全屏播放直播，第一次使用返回手势时，软件自动切换为竖屏布局并在数秒后恢复为全屏，第二次返回才能正常退出。(图2)

### 复现步骤
平板布局下进入任意直播间可见

### 预期行为
按键布局可正常规避任务栏（也许可以通过 平板布局下，直播默认进入全屏 规避这个问题，但会缺失弹幕列表与发送功能）
或是新增左右布局的画面-弹幕列表布局，举例
![example](https://github.com/user-attachments/assets/971f3d3f-b216-47d0-8f80-8c0c349530fa)
去除标签页栏（投喂栏大概也可以去除，把主播信息挪到画面下方）

### 错误日志
App版本：1.0.22+123 (Github release6)
设备型号：Galaxy Tab S8+ (SM-X800)
系统版本：OneUI 6.1.1 (X800ZCS8CXJ7)

### 相关信息
图一，注意右下角
![Screenshot_20241128_233341](https://github.com/user-attachments/assets/e8435032-28a0-4b7c-bcd8-65487f2affc1)

图二，第一次手势返回后短暂停留的竖版界面
![Screenshot_20241128_233519](https://github.com/user-attachments/assets/7ea79f71-d25d-4d18-bd5b-d0ac80f2eb93)

**Comment by bggRGjQaUbCoE** [comment]
横屏≠全屏

**Comment by bggRGjQaUbCoE** [comment]
已添加横屏自动全屏
