### ISSUE TITLE
[Bug] 错误的长回复截断

### ISSUE THREAD

**Issue by Dome-World** [bggRGjQaUbCoE/PiliPalaX#24]
### 问题描述
回复截断不同于原版pilipalax，经常出现直接截断的问题

### 复现步骤
随便一个长评论
![Screenshot_20241129_091922_com.example.pilipalax_edit_204372276622605.jpg](https://github.com/user-attachments/assets/a10cbdf2-f374-43f1-8a0e-5f27b0082797)

### 预期行为
原版的截断
![Screenshot_20241129_091903_com.orz12.PiliPalaX_edit_204384910444892.jpg](https://github.com/user-attachments/assets/f1623458-2095-4e5e-b184-c274da93d260)

末尾加入 ... 会更好。

**Comment by bggRGjQaUbCoE** [comment]
text提前换行了

**Comment by Dome-World** [comment]
> text提前换行了

@bggRGjQaUbCoE 建议在末尾加入 ... 以减少这种割裂感

**Comment by bggRGjQaUbCoE** [comment]
> > text提前换行了
> 
> @bggRGjQaUbCoE 建议在末尾加入 ... 以减少这种割裂感

那不提前换行的text不就多一行...?

**Comment by Dome-World** [comment]
> > > text提前换行了
> > 
> > @bggRGjQaUbCoE 建议在末尾加入 ... 以减少这种割裂感
> 
> 那不提前换行的text不就多一行...?

@bggRGjQaUbCoE 能改回原版pilipala x的模式吗，那个text就没问题，这里改的显示长评论问题会很大。

**Comment by Dome-World** [comment]
> > > > > text提前换行了
> > > > 
> > > > 
> > > > @bggRGjQaUbCoE 建议在末尾加入 ... 以减少这种割裂感
> > > 
> > > 
> > > 那不提前换行的text不就多一行...?
> > 
> > @bggRGjQaUbCoE 能改回原版pilipala x的模式吗，那个text就没问题，这里改的显示长评论问题会很大。
> 
> 自己改

其实我比较想知道你这种评论设计的好处是什么，如果改了会失去什么 ><

**Comment by bggRGjQaUbCoE** [comment]
> > > > > > text提前换行了
> > > > > 
> > > > > 
> > > > > @bggRGjQaUbCoE 建议在末尾加入 ... 以减少这种割裂感
> > > > 
> > > > 
> > > > 那不提前换行的text不就多一行...?
> > > 
> > > 
> > > @bggRGjQaUbCoE 能改回原版pilipala x的模式吗，那个text就没问题，这里改的显示长评论问题会很大。
> > 
> > 
> > 自己改
> 
> 其实我比较想知道你这种评论设计的好处是什么，如果改了会失去什么 ><

避免在maxline换行没有...提示
