### ISSUE TITLE
[FR] 播放器支持 CC字幕字号调整 与 章节分段

### ISSUE THREAD

**Issue by sharkucn** [bggRGjQaUbCoE/PiliPalaX#28]
### 功能描述
默认字幕字号偏小（对比习惯的YouTube大小）
![Screenshot_20241130_213441](https://github.com/user-attachments/assets/2592351b-33b4-4d90-ad2f-3ac31d2828d9)
![Screenshot_20241130_214219_YouTube](https://github.com/user-attachments/assets/d784ed63-51a5-48fe-a02f-27864c357b51)

支持分段便于跳过片头、快速定位感兴趣部分等操作。

### 解决方案
在弹幕设置下方新增字幕设置
![Screenshot_20241130_220453](https://github.com/user-attachments/assets/435c7439-79b0-46d6-9c44-6ebc04559a0b)

类似哔哩哔哩HD的分段展示
![Screenshot_20241130_220133_HD](https://github.com/user-attachments/assets/a01e9577-229b-4ff1-a05e-3385aecf8e43)
![Screenshot_20241130_214047_HD](https://github.com/user-attachments/assets/d5308ed6-ffe4-475a-a1d9-2cb6bc8071e2)

**Comment by Dome-World** [comment]
我觉得cc字幕应该像弹幕一样随全屏变化，目前这个大小挺适合非全屏的，全屏之后就太小了
