### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Shecy084** [bggRGjQaUbCoE/PiliPalaX#31]
### 问题描述
重力的临时全屏全屏弹幕字体大小没有生效

### 复现步骤
在播放视频界面直接旋转手机进入横屏，全屏弹幕字体大小没有生效，要再点一次全屏按钮才会生效

### 预期行为
重力横屏之后能弹幕字体大小和全屏弹幕字体大小设置的一样。

### 相关信息
![Screenshot_2024-12-01-19-26-07-411_com.example.pilipalax.jpg](https://github.com/user-attachments/assets/dad8cfc6-5d9c-4d8b-ae7a-eea4ad493132)

![Screenshot_2024-12-01-19-26-16-752_com.example.pilipalax.jpg](https://github.com/user-attachments/assets/0426b3dc-b222-431c-b52d-55339585caa8)

**Comment by bggRGjQaUbCoE** [comment]
横屏≠全屏

**Comment by Shecy084** [comment]
因为习惯用重力感应横屏看，这样子感觉弹幕有点小，字体调大了竖屏的时候又感觉有点大了
