### ISSUE TITLE
[Bug] iOS 版本在静音模式下部分视频没有声音的问题

### ISSUE THREAD

**Issue by QingRex** [bggRGjQaUbCoE/PiliPalaX#32]
### 问题描述
该问题在原版本的PiliPala 以及后续版本的 PiliPalaX 中都存在以已久，表现为 iOS 在播放部分视频时无法播放声音，此外在切换后台打开其他应用再次切换到 Pilipala 的情况下在静音模式下视频会没有声音。

### 复现步骤
iOS 系统开启静音模式在打开极客湾视频（我关注中他存在问题最明显）时高发无视频声音情况，此时关闭静音模式立即出现声音（基本所有无声音频都可以这样解决）。
### 预期行为
在静音模式下播放视频不会存在此Bug，希冀开发者大佬能够考虑修复下这个基本所有pilipala都存在的问题，十分感谢。

### 错误日志
无日志，测试手机iPhone15PM（ios18.2beta2）

```

```

### 相关信息
我测试的无声音视频：
【官方双语】2024年末装机选购指南#linus谈科技 UP主: LinusTechTips - https://www.bilibili.com/video/BV1KgzfYUEC9
ROG 9 Pro上手体验：用灯效玩游戏是什么感觉？ UP主: 极客湾Geekerwan - https://www.bilibili.com/video/BV1hcSwYREe1

**Comment by bggRGjQaUbCoE** [comment]
无法调试，修不了

**Comment by u3l6** [comment]
问题出现之后 关于-错误日志 里是空的，没办法发日志
