### ISSUE TITLE
[Bug] 账号触发风控使用手机号登录验证码收不到

### ISSUE THREAD

**Issue by cgykcftyi** [bggRGjQaUbCoE/PiliPalaX#33]
### 问题描述
这个问题pilipala（不带X的版本）和官方版都没有，X版有

### 复现步骤
首先用密码登录，提示风控，再用手机号登录，点发送验证码直接显示验证码错误，（我按的的确是发送验证码），之后退出直接用手机号登录，发送按钮能按，但收不到短信。

### 预期行为
风控后能正常用手机号登录

### 错误日志
版本7，Android9 无日志显示

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by bggRGjQaUbCoE** [comment]
等上游更新再合并
