### ISSUE TITLE
[Bug] 观看记录搜索结果无法跳转播放

### ISSUE THREAD

**Issue by sharkucn** [bggRGjQaUbCoE/PiliPalaX#35]
### 问题描述
在观看记录页搜索，得到的结果无法点击跳转播放

### 复现步骤
媒体库 - 观看记录 - 搜索 - 输入搜索内容并得到结果 - 点击任意结果

### 预期行为
搜索结果可以正常跳转播放

### 相关信息
App版本：Github release8
设备型号：Galaxy Tab S8+ (SM-X800)
系统版本：OneUI 6.1.1 (X800ZCS8CXJ7)

![Screenshot_20241202_185514](https://github.com/user-attachments/assets/8b1e49f9-f8ff-4b3b-9d4d-6522a740103e)

**Comment by bggRGjQaUbCoE** [comment]
https://github.com/bggRGjQaUbCoE/PiliPalaX/actions/runs/12114618947
