### ISSUE TITLE
[FR] 将外观恢复到 Release 8

### ISSUE THREAD

**Issue by xuangeyouneihan** [bggRGjQaUbCoE/PiliPalaX#37]
### 功能描述
如题

### 目标
Release 9 的推荐列表里视频信息框和背景没有区分度，比 Release 8 更偏灰色的底栏颜色与几乎纯白的背景也太过单调

Release 9:
![Screenshot_2024-12-16-11-47-12-930_com example pilipalax](https://github.com/user-attachments/assets/1c03d8c1-2e47-426e-96d4-d37f9db9b945)

Release 8:
![Screenshot_2024-12-16-11-58-03-803_com example pilipalax](https://github.com/user-attachments/assets/d85b7c18-2b60-411f-8346-cffd72e90ef4)

### 解决方案
恢复Release 8的外观

### 其他
本应用 Release 8及以前的版本

**Comment by bggRGjQaUbCoE** [comment]
调整应用主题-调色版风格

**Comment by xuangeyouneihan** [comment]
都试过了，没用

**Comment by bggRGjQaUbCoE** [comment]
> 里面所有选项都试过了，没用

OK，调整了动态主题
https://github.com/bggRGjQaUbCoE/PiliPalaX/actions/runs/12345903550

**Comment by xuangeyouneihan** [comment]
OK，这个问题解决了。但似乎调色板风格还是没用，我都切成高对比度了颜色还是没变化，不知道是需要关闭动态取色还是因为 Bug

**Comment by bggRGjQaUbCoE** [comment]
> OK，这个问题解决了。但似乎调色板风格还是没用，我都切成高对比度了颜色还是没变化，不知道是需要关闭动态取色还是因为 Bug

只对自定义颜色生效
