### ISSUE TITLE
[Bug] 使用 App 端推荐时首页推荐里没有动态

### ISSUE THREAD

**Issue by xuangeyouneihan** [bggRGjQaUbCoE/PiliPalaX#40]
### 问题描述
如题，即使开了“推荐流设置”里的“推荐动态”选项也没用

### 复现步骤
在“推荐流设置”里将“首页推荐类型”设置为“app端”，开启“推荐动态”，重启应用

### 预期行为
首页的推荐列表中有动态出现

### 错误日志
无

### 相关信息
PiliPala 上会正常推荐动态

**Comment by bggRGjQaUbCoE** [comment]
没问题

**Comment by xuangeyouneihan** [comment]
啊？那应该是特定几个账号的问题？
