### ISSUE TITLE
[FR] 可否添加一个横屏适配布局下简介自动展开功能

### ISSUE THREAD

**Issue by bbyuyund** [bggRGjQaUbCoE/PiliPalaX#47]
### 功能描述
请提供对所请求功能的清晰描述。
Rt,希望能添加一个自动展开简介的功能，以填充平板布局下的空白区域，谢谢大佬

### 目标
请描述你希望通过这个功能实现的目标。
除了有分p的视频之外，大部分零散的视频在平板的播放ui中都有左下角大片空白，如果简介可以自动展开的话感觉对强迫症患者会友好一些（。开启选项之后，或许可以考虑把切换分p的选项提高到简介上方？

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

闲谈:最近发现大佬这的pilipalax横屏布局下打开简介不会弹出窗口而是置于左下角空白区域了，而且弹幕尺寸调节支持全屏分别调整，真的太会做了😭😭😭，比某哩hd不知道人性化到哪里去了（只有真正在用的人才能做出这么合适的设计），感觉是安卓平板日用最强客户端了（我不知道github这个反馈区能不能写这些杂七杂八的，如果不能很抱歉。）

**Comment by Dome-World** [comment]
@bggRGjQaUbCoE 大佬，我并不建议这样做，因为这样会使一些视频下面的分P和选择合集挤到最下面，并且在16:10的平板上下面并不空，展开反而很乱，现在这样就可以。如果有个人需求应当做成选项，由个人手动开启。

**Comment by bbyuyund** [comment]
> @bggRGjQaUbCoE 大佬，我并不建议这样做，因为这样会使一些视频下面的分P和选择合集挤到最下面，不下滑就发现不了，并且在16:10的平板上下面并不空，展开反而很乱，现在这样就可以。如果有个人需求应当做成选项，比如简介自动展开，由个人手动开启。

谢谢兄弟，我提的建议确实是添加一个开关选项（，我平板是3比2的，下方有一片很大的空🙃，就和现在平板型布局自动切换到评论区的选项一样。况且我在正文里也写了可以考虑把分p按钮提高到简介之上😣（或者右置分两半？），不过当然一切看大佬的考量（，感谢为爱发电。

**Comment by bbyuyund** [comment]
> @bggRGjQaUbCoE 大佬，我并不建议这样做，因为这样会使一些视频下面的分P和选择合集挤到最下面，不下滑就发现不了，并且在16:10的平板上下面并不空，展开反而很乱，现在这样就可以。如果有个人需求应当做成选项，比如简介自动展开，由个人手动开启。

看了新的构建版本，佬确实是把这个功能做成了开关选项，并且可以作用于手机型布局，非常感谢，至少对于我这种不太看相关推荐的来说手机布局开启也是非常好的😘，你也可以不用太担心了。
