### ISSUE TITLE
[FR] 请问能否加回 Release 8 中的背景色状态栏开关

### ISSUE THREAD

**Issue by radixyuan** [bggRGjQaUbCoE/PiliPalaX#49]
### 功能描述
[设置] - [外观设置] - [播放页状态栏显示为背景色]

### 目标
如图
![Screenshot_20241224-163240_PiliPalaX](https://github.com/user-attachments/assets/34b0d71c-8e28-4145-b769-4a503d75db3c)

**Comment by bggRGjQaUbCoE** [comment]
这个实现在ios上有bug
