### ISSUE TITLE
[FR] 清晰度按照网络情况有所区分

### ISSUE THREAD

**Issue by in-out** [bggRGjQaUbCoE/PiliPalaX#52]
### 功能描述
眼馋漫游清晰度设置
在网络为WiFi，或是数据流量的时候
可以分别设置清晰度
比如说
WiFi 1080P
数据流量 480P

### 目标
运营商数据是时节省流量
WiFi下享受高画质

### 解决方案
参照漫游实现？

### 其他
漫游的清晰度设置
现在漫游无法截图

**Comment by in-out** [comment]
神速！
测试了下
视频的设置好像是反了
蜂窝的话走了默认画质

**Comment by bggRGjQaUbCoE** [comment]
> 神速！ 测试了下 视频的设置好像是反了 蜂窝的话走了默认画质

你确定？

**Comment by in-out** [comment]
![Screenshot_20241226_171709.jpg](https://github.com/user-attachments/assets/b0f7bee5-de9e-4d50-88d2-702d7039a5da)

![Screenshot_20241226_171758.jpg](https://github.com/user-attachments/assets/99a68d42-afd4-4969-a8a8-e511e51b3df0)

默认是480
蜂窝是1080
使用数据的时候 走的是默认480


> > 神速！ 测试了下 视频的设置好像是反了 蜂窝的话走了默认画质
> 
> 你确定？

**Comment by in-out** [comment]
> > ![Screenshot_20241226_171709.jpg](https://private-user-images.githubusercontent.com/3615775/398692537-b0f7bee5-de9e-4d50-88d2-702d7039a5da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUzMTgsIm5iZiI6MTczNTIwNTAxOCwicGF0aCI6Ii8zNjE1Nzc1LzM5ODY5MjUzNy1iMGY3YmVlNS1kZTllLTRkNTAtODhkMi03MDJkNzAzOWE1ZGEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMDkyMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzUxZjEyODI0MDZjZDgwNTNkNTIwY2JlNmU2ZWY0N2U0N2UzZjAzOTIzYmI4OTU4MGZhMWIyNjViZTQwNmM1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cGbavi3wCx-RouA5jseVZ-cmDdN4z5Py4ANokeJH5nI)
> > 
> > ![Screenshot_20241226_171758.jpg](https://private-user-images.githubusercontent.com/3615775/398692555-99a68d42-afd4-4969-a8a8-e511e51b3df0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUzMTgsIm5iZiI6MTczNTIwNTAxOCwicGF0aCI6Ii8zNjE1Nzc1LzM5ODY5MjU1NS05OWE2OGQ0Mi1hZmQ0LTQ5NjktYThhOC1lNTExZTUxYjNkZjAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMDkyMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzJiODY0YTJiY2FmMTljZmRkYmZkYzc4Mjc0ZGZlNTY2NjI4OWMyYjg4N2RmN2Y0OGYyYmIxNDg2ZDdlM2ZmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.C29M9m06RQxCvQdj-lUi_0TEKwn8PXYZq16OU4x8sYk)
> > 
> > 默认是480 蜂窝是1080 使用数据的时候 走的是默认480
> > 
> > > > 神速！ 测试了下 视频的设置好像是反了 蜂窝的话走了默认画质
> > > 
> > > 
> > > 你确定？
> 
> 那这是`connectivity_plus`库判断问题

奇怪的是 声音的设定好像是对的

**Comment by bggRGjQaUbCoE** [comment]
> > > ![Screenshot_20241226_171709.jpg](https://private-user-images.githubusercontent.com/3615775/398692537-b0f7bee5-de9e-4d50-88d2-702d7039a5da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUzMTgsIm5iZiI6MTczNTIwNTAxOCwicGF0aCI6Ii8zNjE1Nzc1LzM5ODY5MjUzNy1iMGY3YmVlNS1kZTllLTRkNTAtODhkMi03MDJkNzAzOWE1ZGEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMDkyMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzUxZjEyODI0MDZjZDgwNTNkNTIwY2JlNmU2ZWY0N2U0N2UzZjAzOTIzYmI4OTU4MGZhMWIyNjViZTQwNmM1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cGbavi3wCx-RouA5jseVZ-cmDdN4z5Py4ANokeJH5nI)
> > > ![Screenshot_20241226_171758.jpg](https://private-user-images.githubusercontent.com/3615775/398692555-99a68d42-afd4-4969-a8a8-e511e51b3df0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUzMTgsIm5iZiI6MTczNTIwNTAxOCwicGF0aCI6Ii8zNjE1Nzc1LzM5ODY5MjU1NS05OWE2OGQ0Mi1hZmQ0LTQ5NjktYThhOC1lNTExZTUxYjNkZjAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMDkyMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzJiODY0YTJiY2FmMTljZmRkYmZkYzc4Mjc0ZGZlNTY2NjI4OWMyYjg4N2RmN2Y0OGYyYmIxNDg2ZDdlM2ZmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.C29M9m06RQxCvQdj-lUi_0TEKwn8PXYZq16OU4x8sYk)
> > > 默认是480 蜂窝是1080 使用数据的时候 走的是默认480
> > > > > 神速！ 测试了下 视频的设置好像是反了 蜂窝的话走了默认画质
> > > > 
> > > > 
> > > > 你确定？
> > 
> > 
> > 那这是`connectivity_plus`库判断问题
> 
> 奇怪的是 声音的设定好像是对的

不要好像

**Comment by bggRGjQaUbCoE** [comment]
> 神速！ 测试了下 视频的设置好像是反了 蜂窝的话走了默认画质

https://github.com/bggRGjQaUbCoE/PiliPalaX/actions/runs/12503670734
试下这个，改成判断是否是WiFi

**Comment by in-out** [comment]
> > 神速！ 测试了下 视频的设置好像是反了 蜂窝的话走了默认画质
> 
> https://github.com/bggRGjQaUbCoE/PiliPalaX/actions/runs/12503670734
> 试下这个，改成判断是否是WiFi

可以了 多谢d佬
