### ISSUE TITLE
[FR] 请问有没有可能自选字体或跟随系统字体包？现在app好像没办法应用系统字体……

### ISSUE THREAD

**Issue by JinZhong-RouSong** [bggRGjQaUbCoE/PiliPalaX#53]
### 功能描述
希望APP能支持系统字体或自选字体

### 目标
将现有app的字体更换掉，目前的对我太细了……想换自己系统这样更粗一点的

### 解决方案
只是建议，感谢大佬做第三方

### 其他
哔哩哔哩、bilibili谷歌版、漫游

**Comment by bggRGjQaUbCoE** [comment]
https://github.com/flutter/flutter/issues/48381

**Comment by DwainZwerg** [comment]
@bggRGjQaUbCoE There is a plugin: https://github.com/re7gog/android_system_font

**Comment by bggRGjQaUbCoE** [comment]
> [@bggRGjQaUbCoE](https://github.com/bggRGjQaUbCoE) There is a plugin: https://github.com/re7gog/android_system_font

Not interested
