### ISSUE TITLE
[FR] 默认音质选项建议

### ISSUE THREAD

**Issue by hou9999** [bggRGjQaUbCoE/PiliPalaX#56]
![Screenshot_20241226-200102](https://github.com/user-attachments/assets/80d988cd-9f43-478b-8234-12e972f07841)
设置内默认音质选项，hires优先级是高于杜比全景声的，可杜比全景声音质是优于hires的
这导致默认音质选择杜比全景声时，播放hires视频时，音质会被自动切换到192k，如下图所示
![Screenshot_20241226-200400](https://github.com/user-attachments/assets/bcbba931-fc55-4fd2-a9f4-0319e340ec14)
建议：把杜比全景声优先级最高，或者添加首选音质和次选音质（参考视频解码选择方式）

还有最新版本弹幕行间距太大，建议添加可调节行间距选项

**Comment by bggRGjQaUbCoE** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/video/videostream_url.md

## 视频伴音音质代码

| 值    | 含义 |
| ----- | ---- |
| 30216 | 64K  |
| 30232 | 132K |
| 30280 | 192K |
| 30250 | 杜比全景声 |
| 30251 | Hi-Res无损 |
