### ISSUE TITLE
[Bug] 卡死

### ISSUE THREAD

**Issue by xfdyd** [bggRGjQaUbCoE/PiliPalaX#57]
### 问题描述
退出详情页卡死。经常发生。

### 错误日志
PiliPalaX错误日志
********************
------- 设备信息 -------
id: TP1A.220624.014
board: unknown
bootloader: unknown
brand: LeBest
device: Q6558
display: LeBest_L202306_V1.0
fingerprint: LeBest/L202306/Q6558:13/TP1A.220624.014/1703678106:user/release-keys
hardware: agn2263SHP
host: agenewby
isPhysicalDevice: true
manufacturer: LeBest
model: L202306
product: L202306
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 1703678106
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-07-05
------- 应用信息 -------
environment: release
version: 1.0.22
appName: PiliPalaX
buildNumber: 123
packageName: com.example.pilipalax
---------- 错误信息 ----------
"RcmdController" not found. You need to call "Get.put(RcmdController())" or "Get.lazyPut(()=>RcmdController())"
------- 错误堆栈 -------
#0      GetInstance.find (package:get/get_instance/src/get_instance.dart:306)
#1      Inst.find (package:get/get_instance/src/extension_instance.dart:69)
#2      Inst.find.<anonymous closure> (package:get/get_instance/src/extension_instance.dart:69)
#3      HomeController.animateToTop (package:PiliPalaX/pages/home/controller.dart:61)
#4      _MainAppState.setIndex (package:PiliPalaX/pages/main/view.dart:96)
#5      _BottomNavigationBarState._createTiles.<anonymous closure> (package:flutter/src/material/bottom_navigation_bar.dart:1110)
#6      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1176)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313)
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:246)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:703)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#14     _LinkedHashMapMixin.forEach (dart:_compact_hash:726)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:502)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:482)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:457)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306)
#24     _invoke1 (dart:ui/hooks.dart:328)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:450)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
------- CUSTOM INFO -------

**Comment by bggRGjQaUbCoE** [comment]
跟这个log无关，看上游说是pip问题

**Comment by hou9999** [comment]
8gen3，在播放360p/1080p高码率/4k视频下，均有帧率不稳定、花屏、画面卡死、闪退、gpu频率负载异常的问题
未开启弹幕，使用hevc解码
这些问题在5天前发布的1.1.0+175原版pilipalax和上一版本的pilipalax mod版本上都没有出现

**Comment by xfdyd** [comment]
容我再补充两个日志

PiliPalaX错误日志
********************
------- 设备信息 -------
id: TP1A.220624.014
board: unknown
bootloader: unknown
brand: LeBest
device: Q6558
display: LeBest_L202306_V1.0
fingerprint: LeBest/L202306/Q6558:13/TP1A.220624.014/1703678106:user/release-keys
hardware: agn2263SHP
host: agenewby
isPhysicalDevice: true
manufacturer: LeBest
model: L202306
product: L202306
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 1703678106
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-07-05
------- 应用信息 -------
environment: release
version: 1.0.22
appName: PiliPalaX
buildNumber: 123
packageName: com.example.pilipalax
---------- 错误信息 ----------
"RcmdController" not found. You need to call "Get.put(RcmdController())" or "Get.lazyPut(()=>RcmdController())"
------- 错误堆栈 -------
#0      GetInstance.find (package:get/get_instance/src/get_instance.dart:306)
#1      Inst.find (package:get/get_instance/src/extension_instance.dart:69)
#2      Inst.find.<anonymous closure> (package:get/get_instance/src/extension_instance.dart:69)
#3      HomeController.animateToTop (package:PiliPalaX/pages/home/controller.dart:61)
#4      _MainAppState.setIndex (package:PiliPalaX/pages/main/view.dart:96)
#5      _MainAppState.build.<anonymous closure> (package:PiliPalaX/pages/main/view.dart:154)
#6      PopScope._callPopInvoked (package:flutter/src/widgets/pop_scope.dart:143)
#7      _PopScopeState.onPopInvokedWithResult (package:flutter/src/widgets/pop_scope.dart:178)
#8      ModalRoute.onPopInvokedWithResult (package:flutter/src/widgets/routes.dart:1864)
#9      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5356)
<asynchronous suspension>
#10     WidgetsBinding.handlePopRoute (package:flutter/src/widgets/binding.dart:862)
<asynchronous suspension>
#11     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571)
<asynchronous suspension>
#12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:622)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by xfdyd** [comment]
PiliPalaX错误日志
********************
------- 设备信息 -------
id: TP1A.220624.014
board: unknown
bootloader: unknown
brand: LeBest
device: Q6558
display: LeBest_L202306_V1.0
fingerprint: LeBest/L202306/Q6558:13/TP1A.220624.014/1703678106:user/release-keys
hardware: agn2263SHP
host: agenewby
isPhysicalDevice: true
manufacturer: LeBest
model: L202306
product: L202306
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 1703678106
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-07-05
------- 应用信息 -------
environment: release
version: 1.0.22
appName: PiliPalaX
buildNumber: 123
packageName: com.example.pilipalax
---------- 错误信息 ----------
Bad state: No element
------- 错误堆栈 -------
#0      List.single (dart:core-patch/growable_array.dart:354)
#1      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:173)
#2      PageController.page (package:flutter/src/widgets/page_view.dart:184)
#3      _MainAppState._checkDefaultSearch (package:PiliPalaX/pages/main/view.dart:74)
#4      _MainAppState.didChangeAppLifecycleState (package:PiliPalaX/pages/main/view.dart:66)
#5      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:977)
#6      ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:289)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:622)
#9      _invoke2 (dart:ui/hooks.dart:344)
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#11     _Channel.push (dart:ui/channel_buffers.dart:135)
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:343)
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:758)
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:257)
------- CUSTOM INFO -------

**Comment by hou9999** [comment]
已经解决了啊https://github.com/bggRGjQaUbCoE/PiliPalaX/commit/821a6ad4b2f891b04cc142110bf8cc56a41c9a7a

**Comment by xfdyd** [comment]
> 已经解决了啊[821a6ad](https://github.com/bggRGjQaUbCoE/PiliPalaX/commit/821a6ad4b2f891b04cc142110bf8cc56a41c9a7a)

哦，谢谢你！我也看不懂。
