### ISSUE TITLE
[Bug] 图片不能正常显示

### ISSUE THREAD

**Issue by Users1437** [bggRGjQaUbCoE/PiliPalaX#59]
### 问题描述
最新版所有图片左上角都有花屏马赛克
![Screenshot_2024-12-28-00-36-21-109_com.example.pilipalax.jpg](https://github.com/user-attachments/assets/13668b97-54aa-4049-8fd5-01a9b0ceb9cf)

用过其它项目出过一样的情况，那位开发者修复的日志是"修复由于flutter新sdk版本 默认启用叶轮impeller,导致部分机型或者系统渲染马赛克卡顿的问题"，不知道是不是同一原因
机型小米15

**Comment by bggRGjQaUbCoE** [comment]
impeller 已经关了，考虑回退
