### ISSUE TITLE
[Bug] 开启合集列表显示在tap栏后，视频分p仍为横向滑动

### ISSUE THREAD

**Issue by xumidcm** [bggRGjQaUbCoE/PiliPalaX#67]
### 问题描述
开启合集列表显示在tap栏后，视频分p仍为横向排列

### 复现步骤
打开合集列表显示在tap栏后打开一个多p视频

### 预期行为
希望也能像合集一样展示

### 错误日志
app版本release13，系统安卓9

```

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。
![IMG_20241229_143611](https://github.com/user-attachments/assets/ead102f0-55b1-482d-a0ed-a0af1ed34973)
![Screenshot_20241229-144208](https://github.com/user-attachments/assets/24d9c15d-c7ba-4de0-b4a9-41d14a1d3e4b)

**Comment by bggRGjQaUbCoE** [comment]
符合预期，因为有的视频同时存在分P和合集
