### ISSUE TITLE
[Bug] 开启无痕模式后切换界面会导致无痕模式按钮重置

### ISSUE THREAD

**Issue by ajdgsu** [bggRGjQaUbCoE/PiliPalaX#79]
### 问题描述
当在任意视频右下角复选框内选择"进入无痕模式"(临时)后，进行页面切换(包括进入视频，打开设置选项等)都会导致无痕模式开关变回"进入无痕模式" (应为退出无痕模式)
或者在主页视频复选框内选择"进入无痕模式"，再打开复选框后仍然显示为"进入无痕模式"

### 预期行为
无痕模式开启时则无痕开关永远显示为"退出无痕模式"，反之亦然

**Comment by bggRGjQaUbCoE** [comment]
上游写法问题
